### ISSUE TITLE
BCC replace TO

### ISSUE THREAD

**Issue by LEloffel** [darrencauthon/csharp-sparkpost#43] opened 2016-04-21 14:55 UTC
Hi,

The code below should add an email address to TO field, and one to BCC, but the BCC seems to overwrite the TO field.

`            var transmission = new Transmission();

```
        Address emailaddressTo = new Address();
        emailaddressTo.Email = strTO;
        emailaddressTo.Name = strNameToSendEmailTo;

        var listRepientsTo = new Recipient();
        listRepientsTo.Address = emailaddressTo;
        listRepientsTo.Type = RecipientType.To;
        transmission.Recipients.Add(listRepientsTo);

        Address emailaddressBCC = new Address();
        emailaddressBCC.Email = strBCC;
        emailaddressBCC.Name = "Assessment";

        var listRepientsBCC = new Recipient();
        listRepientsBCC.Address = emailaddressBCC;
        listRepientsBCC.Type = RecipientType.BCC;
        transmission.Recipients.Add(listRepientsBCC);
```

`

**Comment by darrencauthon** [comment] 2016-04-21 17:48
I've been discussing this on #14.  I cannot reproduce this issue at all.  I've sent emails, templates, etc.... I get both emails.

Plus, like I mentioned in the other thread, ```To``` and ```BCC``` are treated the same.  The only change in behavior is for ```CC```.

![fullscreen_042116_124118_pm](https://cloud.githubusercontent.com/assets/148768/14718957/223c8a68-07bf-11e6-86b3-0360a32cdc8a.jpg)

I'm closing this ticket just because I cannot reproduce the issue.  If I can get a failing unit test or an example I can reproduce, I'd be happy to reopen.

**Comment by LEloffel** [comment] 2016-04-26 12:03
Hi,

I did some further testing and I'm seeing the following:
1. if no HeaderTo is set, on any To, CC, or BCC address:
  - the To email received looks ok
  -  the CC email received has the CC email address in the TO field, and obviously the CC fields of email
 - the BCC email received has the BCC email address in the TO field. CC email is fine.

So CC fields seems fine, but in CC and BCC email copy, the To field is wrong.

2. if all the HeaderTo attributes is set, on all the To, CC, or BCC address:
  - the To email received looks ok
  -  the CC email received has the TO email address in the TO field (however the Name of To is the CC email address), and obviously the CC fields of email
 - the BCC email received has the BCC email name in the TO field (although the email address is correct). CC email is fine.

Not sure if you have tested with the Name attributes. So a solution is to always specify the HeaderTo field and point to the TO email address.  Not sure if the changing of the names in the CC and BCC email is expected behaviour.

It also seems even if CC name is set, it never shows.

**Comment by gajanan414** [comment] 2016-05-10 17:20
Hi ,

This is my sample code i am not able to append cc using a template 
can u help me out 

**here is my Code : **

 class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        private static async Task<bool> MainAsync()
        {
            var apiKey = string.Empty;
            var client = new Client(apiKey);
            try
            {
                var transmission = new SparkPost.Transmission();
                var substitutionData = new Dictionary<string, object>() { { "To", "Trinath" }, { "InvoiceNumber", "100021" }, { "TotalAmount", "10254.50" } };
                transmission.Recipients = new List<Recipient>() {
                    new Recipient() { Address = new Address() { Email = "trinathm@simha.in", HeaderTo = "trinathm@simha.in" }, SubstitutionData = substitutionData },
                    new Recipient() { Address = new Address() { Email = "prasadv@simha.in", HeaderTo = "trinathm@simha.in" }, Type = RecipientType.CC, SubstitutionData = substitutionData } };
                transmission.Content.TemplateId = "invoice";
                transmission.Content.From.Email = "support@simha.in";
                var result = await client.Transmissions.Send(transmission);
                return result.StatusCode == System.Net.HttpStatusCode.OK;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }


thank you

**Comment by darrencauthon** [comment] 2016-05-10 17:37
@gajanan414 I hope you don't mind, but I edited your comment to put in the three tildes before and after the code.

Those tildes tell Github that it's a code block, and Github will show the code accordingly.

**Comment by trinathm** [comment] 2016-06-01 17:06
Any update on this issue. I am still facing the CC issue. Users given in CC are receiving the emails as CC.

**Comment by trinathm** [comment] 2016-06-01 17:09
@darrencauthon can you share the sample code you have used to test CC and BCC for sending emails using templates. That may help us to make sure if we making any mistakes.

**Comment by darrencauthon** [comment] 2016-06-01 17:40
@trinathm I'll put something together to show how I do it.

But I have to say:  I don't use BCC, because BCC is irrelevant to email services like SparkPost.   I've probably already said this above or in other tickets, but every "To" recipient is the equivalent of a "BCC" because SparkPost sends separate emails to each recipient.

SparkPost is not like Outlook where you put five people in the "To" and one email is sent to all five (with everybody seeing each other).  SparkPost will send five separate emails to each "To" recipient, alone (so nobody can see each other).  

So, effectively, every person is a "BCC" because they can't see each other.

But CC is different, and I can provide an example for that.  Just give me a bit.

**Comment by darrencauthon** [comment] 2016-06-01 17:41
Actually, @trinathm , I think someone has already done this.  Check out these samples from @ewandennis :  https://github.com/SparkPost/csharp-sparkpost/tree/master/examples

**Comment by darrencauthon** [comment] 2016-06-01 17:43
I'd read all of the code that @ewandennis , but it looks like this is all a BCC is?  Just changing the header-to?  Hmm....

```c#
			var bcc = new Recipient()
			{
				Address = new Address()
				{
					Email = bccAddr,
					HeaderTo = toAddr
				}
			};
			trans.Recipients.Add(bcc);
```

**Comment by trinathm** [comment] 2016-06-01 19:04
@darrencauthon I totally understand that part. Lets not consider BCC into this for sometime. The sample shared by @ewandennis is not using templates for sending emails with CC. Sending email using Templates and CC is not working. No where I can see that working examples 

It would be greatfull, If I can get working examples of sending email with templates and CC.

**Comment by trinathm** [comment] 2016-06-01 19:07
When we try to send emails using templates and Recipients in CC, Recipients in CC are not receiving the emails, so that was the reason I am asking for some working sample

**Comment by asherber** [comment] 2017-01-18 23:27
I think the SparkPost API totally botches this functionality. I get that to them a recipient is just a recipient, and everything else is playing with the To and CC headers, but that's not how a user thinks. A user should rarely have to know about the `Address.HeaderTo`.

It would be nice if the library would scan the list of recipients and do the following, probably as a helper method:

1. Concatenate the list of addresses for all To recipients
1. For each CC recipient, add the recipient's address to the CC header (library already does this)
1. For each To, CC, and BCC recipient, set `HeaderTo` to the list of To recipients

This is how a normal user of email would expect things to get mapped onto a normal email.

The reason I think this should be a helper method is that there are legitimate cases where a user wants to use a single transmission to send the identical email content to multiple To recipients individually, so always setting `HeaderTo` as described above would not be desired behavior.

@darrencauthon Any objection if I add a method like this, to handle 1 and 3? I'm thinking something like `Transmission.Recipients.SetHeaderTo()`, though that's not quite the right name.

(This doesn't really relate to templates, but it does address the original issue in this thread.)

**Comment by asherber** [comment] 2017-01-20 02:57
I've been doing some playing with this, and SparkPost is even more messed up than I realized.

1. Multiple (comma-delimited) values in `header_to` are not allowed, and you can't explicitly set a `To` header in `content`. This means that you can't have a message which is "addressed" to multiple people, as you can from an SMTP client. (@darrencauthon points this out above as well.)
1. An email address in `header_to` only overrides the `email` part of the address, so that the header will still use the `name` from the address. And you can't specify both a name and address in `header_to`.

I understand the first point -- I guess the whole point of transactional email is to send an email to one specific individual, so you'd never have a case with several people on the `To` line. 

But the second point is a hassle. In a proper Cc or Bcc, the copied recipient sees a message which is addressed to the primary recipient. IOW, if I send a message to Bob and Cc John, the message in John's Inbox appears to be addressed to Bob, and it has John's name and address only in the Cc header. With SparkPost, in order to accomplish this, I have to set Johns's address like this:
```javascript
"address": {
  "name": "Bob", 
  "email": "john@example.com",
  "header_to": "bob@example.com"
}
```
Similarly, the auto Cc handling in this library doesn't let me include John's name along with his address in the Cc header – because in order for the To header to read correctly, John's name isn't provided anywhere in the address object. I can get this to work the way I want by setting the Cc header myself (using John's name).

**Comment by darrencauthon** [comment] 2017-01-20 03:25
I just got home. I'll be taking a look at this in the next hour or two. 
I had my head deep in how they did this, I just have to reload it in my brain. :)






On Thu, Jan 19, 2017 at 8:57 PM -0600, "asherber" <notifications@github.com> wrote:












I've been doing some playing with this, and SparkPost is even more messed up than I realized.

Multiple (comma-delimited) values in header_to are not allowed, and you can't explicitly set a To header in content. This means that you can't have a message which is "addressed" to multiple people, as you can from an SMTP client. (@darrencauthon points this out above as well.)
An email address in header_to only overrides the email part of the address, so that the header will still use the name from the address. And you can't specify both a name and address in header_to.



I understand the first point -- I guess the whole point of transactional email is to send an email to one specific individual, so you'd never have a case with several people on the To line.


But the second point is a hassle. In a proper Cc or Bcc, the copied recipient sees a message which is addressed to the primary recipient. IOW, if I send a message to Bob and Cc John, the message in John's Inbox appears to be addressed to Bob, and it has John's name and address only in the Cc header. With SparkPost, in order to accomplish this, I have to set Johns's address like this:
"address": {
  "name": "Bob", 
  "email": "john@example.com",
  "header_to": "bob@example.com"
}


Similarly, the auto Cc handling in this library doesn't let me include John's name along with his address in the Cc header – because in order for the To header to read correctly, John's name isn't provided anywhere in the address object. I can get this to work the way I want by setting the Cc header myself (using John's name).

**Comment by asherber** [comment] 2017-01-20 03:36
No rush on this – my post was mostly pointing out deficiencies in the API and setting things down for the record. I don't think there's anything this library could do to improve things without diverging some from the structure of the API, which I know you are hesitant to do. I really wish SparkPost had provided separate To, CC, and BCC fields, like all the other ESPs, and then handled all the wiring behind the scenes. It's not a good tradeoff to ask users to do all that work, in exchange for a small amount of extra flexibility that almost no one will need.

**Comment by asherber** [comment] 2017-01-20 03:57
Here's how to do a "proper" cc and bcc with this library:

```csharp
transmission.Recipients.Add(new Recipient
{
    Address = new Address
    {
        Email = "to@thisperson.com",
        Name = "To Person"
    }
});

transmission.Recipients.Add(new Recipient
{
    Address = new Address
    {
        Email = "cc@thatperson.com",
        Name = "To Person",
        HeaderTo = "to@thisperson.com"
    }
});

transmission.Recipients.Add(new Recipient
{
    Address = new Address
    {
        Email = "bcc@thatperson.com",
        Name = "To Person",
        HeaderTo = "to@thisperson.com"
    }
});

transmission.Content.Headers.Add("CC", "CC Person <cc@thatperson.com>");
```
All 3 recipients will get an email that looks like this:
```
To: To Person <to@thisperson.com>
CC: CC Person <cc@thatperson.com>
```
There's no good way for the library to do this automagically at present, because the name "CC Person", which is needed for the CC header, doesn't appear in any of the `Recipient` objects. There would need to be at least one extra property and/or some new methods.

**Comment by darrencauthon** [comment] 2017-01-20 13:46
@asherber I'm sorry -- I took two TKD classes last night.  I was going to pull out my laptop after I took a short break, and I just fell asleep.

This issue sort of jogged my memory.  I remember trying to do something with my "CC Handling" class.  Doesn't this handle the situation?  https://github.com/darrencauthon/csharp-sparkpost/blob/129ed3f0b503d73b3f3a8c9bd524c875e4c8a556/src/SparkPost/CcHandling.cs

I agree with what you're saying about the API.  The API seems very focused on the technical details of sending an email, rather than the users.  But what's the point of an API if it's not geared towards users?  I wrote this library after getting some help from SparkPost as to how it is supposed to work.  It means that you should be able to set the To/CC/BCC fields on the recipient, and the library should accommodate you.

**Comment by asherber** [comment] 2017-01-20 14:19
The CC handling class does part of the work – it creates the CC header, although it doesn't add names to the header. But it doesn't play well if there are names on the addresses, as @LEloffel noticed, and it relies on the user to set `HeaderTo` correctly, which I think should be avoided if possible.

I have some code which I'll put into a Gist later this morning which addresses (no pun intended) these issues. It accomplishes what I think a normal user would expect by just setting the `RecipientType`.

**Comment by asherber** [comment] 2017-01-20 15:37
See https://gist.github.com/asherber/f12418c5ec92589aaff877f179b1118b  The first file is the code, and the second shows the result.

I coded this working directly on the transmission, because it was easier, but it could also be written to operate on the `Dictionary` produced by the mapper, so that the original transmission remains unaltered; that would allow for a flag like `Transmission.Options.DistributeRecipients` to trigger this behavior so that it stays optional. (Or this could all be a method that the user chooses to invoke, knowing that he's altering the transmission.)

I do think that having this as optional in some way is preferable; it may not be desirable in all cases.

**Comment by asherber** [comment] 2017-01-21 03:08
I added a code file that operates on the mapped dictionary instead of the original transmission.

**Comment by asherber** [comment] 2017-01-21 12:57
Actually, I'm thinking now that this _should_ be standard behavior, if any recipients are marked as CC or BCC – anyone who wants to manage all of this by hand would just keep all recipients as To and then do whatever they want with address fields and headers. I'm going to add some tests and submit a PR, and we can refine the idea over there.

**Closed** 2017-01-24 14:49 UTC
Labels: duplicate, help wanted

**Comment by darrencauthon** [comment] 2017-01-25 15:09
@LEloffel Can you try the latest library, version 1.13.0?  This issue should be resolved for you now.
