### ISSUE TITLE
MessageEvents quering Issue

### ISSUE THREAD

**Issue by JoseAntonioTorresEspinoza** [darrencauthon/csharp-sparkpost#93] opened 2016-06-14 23:26 UTC
I have an error calling the next method:

**Error catched: One or multiple errors have occurred.**

public void Events()
{
            var client = new Client("MY_API_KEY");

            var query = new MessageEventsQuery();
            query.Recipients = new List<string>() { "mail@gmail.com" };
            query.TransmissionIds = new List<string>(){ "00000000000000000" };
            query.From = DateTime.Parse("2016-01-01T00:00");
            query.To = DateTime.Now;
            query.Page = 25;
            query.PerPage = 100;
            try
            {
                ListMessageEventsResponse Response = client.MessageEvents.List(query).Result;
            }catch(Exception e)
            {

            }
}

can help me somebody?

**Comment by darrencauthon** [comment] 2016-06-15 03:56
What error are you getting?

**Comment by JoseAntonioTorresEspinoza** [comment] 2016-06-15 14:02
![message_events_list](https://cloud.githubusercontent.com/assets/4520313/16082602/a4b46aea-32d7-11e6-8f56-af5cbf0c9afb.png)

**Comment by darrencauthon** [comment] 2016-06-16 03:26
The first thing I would try is removing the date filters. Does that fix the error?

**Comment by JoseAntonioTorresEspinoza** [comment] 2016-06-16 14:14
I removed the data filters but I still getting the error.
![message_envents_list_2](https://cloud.githubusercontent.com/assets/4520313/16119785/a0ac0bee-33a2-11e6-826f-7886418326c3.png)
![message_envents_list_3](https://cloud.githubusercontent.com/assets/4520313/16119784/a0a8e22a-33a2-11e6-85f1-8a43c2d53175.png)

**Comment by darrencauthon** [comment] 2016-06-18 19:35
Just getting back from vacation...

I asked you to look at the date filters because I've seen discrepancies between the format of date/times in the SparkPost HTTP API.  Just a shot in the dark, but that doesn't seem to be a problem.

I tried my own API key, firing a transmission and then querying for the message events.  I had no problem using the same query parameters.   The screenshot is below.  

Since all messages are sent through C#'s async, you might have to look at ```InnerException``` on the exception object you get more specific results.  I can't read spanish, but that looks like the AggregateException that sometimes wraps these types of exceptions.


![fullscreen_061816_023011_pm](https://cloud.githubusercontent.com/assets/148768/16173261/2b9f1290-3561-11e6-9895-0bc7fef164d6.jpg)

**Comment by darrencauthon** [comment] 2016-06-18 19:36
If you can provide more information regarding this exception, please feel free to reopen this issue.  Or if you come to a resolution, please share here in case someone else searches for the same issue.

I'm going to close this ticket only because the API seems to be working ok and I can't reproduce the issue.

**Closed by darrencauthon** 2016-06-18 19:36 UTC

**Comment by JoseAntonioTorresEspinoza** [comment] 2016-06-21 14:36
Sorry I read **data** filters, but I follow your example and is the same Error. I cant get Message Events of a transmission, the InnerException is the next:
![message_envents_list_4](https://cloud.githubusercontent.com/assets/4520313/16232891/e4bdde14-3791-11e6-99f7-f054506e9392.png)

**Comment by csprofiles-sowens** [comment] 2016-06-21 14:41
Try checking your api key and the permissions assigned to it.  You're getting a 403 forbidden error indicating that one or both of these is incorrect.

**Comment by JoseAntonioTorresEspinoza** [comment] 2016-06-21 15:20
Thank you csprofiles-sowens that is the answer. I didn't know that the ApiKey had permissions to assign to it. Sorry darrentcauthon, that was not a API issue.

**Comment by darrencauthon** [comment] 2016-06-21 15:24
No problem @JoseAntonioTorresEspinoza .  Thanks @csprofiles-sowens
